export const CALL_API = Symbol('Call API');
export const API_SYNC_TYPE = Symbol('API Sync Type');
export const TYPE_REQUEST = 'REQUEST';
export const TYPE_SUCCESS = 'SUCCESS';
export const TYPE_FAILURE = 'FAILURE';
export const DEV_REQ_HOST = 'http://localhost:8081/';

export const UPDATE_PASS = 'UPDATE_PASS';
export const VALIDATE_PASS = 'VALIDATE_PASS';

export const LOAD_USER = 'LOAD_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const HEADER_RESET = 'HEADER_RESET';


export const NAV_LIST = 'NAV_LIST';
export const NAV_CHG_NUM = 'NAV_CHG_NUM';

export const BANNER = 'BANNER';
export const BANNER_CHG_NUM = 'BANNER_CHG_NUM';

export const SELECT_DATA = 'SELECT_DATA';

export const LIST_ENT = 'LIST_ENT';
export const LIST_ENT_RELOAD = 'LIST_ENT_RELOAD';
export const LIST_ENT_QUERY = 'LIST_ENT_QUERY';

export const ENT_BIND = 'ENT_BIND';
export const ENT_BIND_RESET = 'ENT_BIND_RESET';

export const SUSPEND_WORK = 'SUSPEND_WORK';
export const SUSPEND_WORK_RESET = 'SUSPEND_WORK_RESET';

export const ARCHIVE_UPDATE = 'ARCHIVE_UPDATE';
export const ARCHIVE_FINISH = 'ARCHIVE_FINISH';
export const ARCHIVE_ADD = 'ARCHIVE_ADD';
export const ARCHIVE_ACTION_RESET = 'ARCHIVE_ACTION_RESET';
export const ARCHIVE_DETAIL = 'ARCHIVE_DETAIL';
export const ARCHIVE_DETAIL_RESET = 'ARCHIVE_DETAIL_RESET';
export const ARCHIVE_SET_PROTOCOL = 'ARCHIVE_SET_PROTOCOL';
export const ARCHIVE_SET_CHECK = 'ARCHIVE_SET_CHECK';

export const LIST_BY_ARCHIVE = 'LIST_BY_ARCHIVE';
export const EVIDENCE_DELETE = 'EVIDENCE_DELETE';

export const INVESTIGATION_LIST = 'INVESTIGATION_LIST';
export const INVESTIGATION_SAVE = 'INVESTIGATION_SAVE';
export const INVESTIGATION_DETAIL = 'INVESTIGATION_DETAIL';
export const INVESTIGATION_UPDATE = 'INVESTIGATION_UPDATE';
export const INVESTIGATION_ACTION_RESET = 'INVESTIGATION_ACTION_RESET';

export const MEDIATE_SAVE = 'MEDIATE_SAVE';
export const MEDIATE_LIST = 'MEDIATE_LIST';
export const MEDIATE_DETAIL = 'MEDIATE_DETAIL';
export const MEDIATE_UPDATE = 'MEDIATE_UPDATE';
export const MEDIATE_ACTION_RESET = 'MEDIATE_ACTION_RESET';

export const PROTOCOL_DETAIL = 'PROTOCOL_DETAIL';
export const PROTOCOL_SAVE = 'PROTOCOL_SAVE';
export const PROTOCOL_UPDATE = 'PROTOCOL_UPDATE';
export const PROTOCOL_ACTION_RESET = 'PROTOCOL_ACTION_RESET';

export const CHECKVISIT_SAVE = 'CHECKVISIT_SAVE';
export const CHECKVISIT_DETAIL = 'CHECKVISIT_DETAIL';
export const CHECKVISIT_UPDATE = 'CHECKVISIT_UPDATE';
export const CHECKVISIT_ACTION_RESET = 'CHECKVISIT_ACTION_RESET';

